package com.bheemnagartimes.news.controller;
import com.bheemnagartimes.news.model.*; import com.bheemnagartimes.news.service.*; import jakarta.servlet.http.HttpSession; import jakarta.validation.Valid; import org.springframework.beans.factory.annotation.Value; import org.springframework.http.*; import org.springframework.stereotype.Controller; import org.springframework.ui.Model; import org.springframework.validation.BindingResult; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.MultipartFile; import java.io.IOException;
@Controller public class NewsController {
private final ArticleGeneratorService generator; private final FileStorageService storage; private final PdfService pdfService;
@Value("${news.brand:भीमनगर टाइम्स}") private String brand; @Value("${news.tagline:सबकी नजर, सबकी खबर}") private String tagline; @Value("${news.location:भीमनगर | उत्तर प्रदेश}") private String location; @Value("${news.slogan:निष्पक्ष, निर्भीक, जनहित में समर्पित}") private String slogan;
public NewsController(ArticleGeneratorService g,FileStorageService s,PdfService p){generator=g;storage=s;pdfService=p;}
@GetMapping("/") public String home(Model model){if(!model.containsAttribute("newsRequest"))model.addAttribute("newsRequest",new NewsRequest());addBrand(model);return "index";}
@PostMapping("/generate") public String generate(@Valid NewsRequest request,BindingResult errors,@RequestParam(value="mainImage",required=false) MultipartFile mainImage,@RequestParam(value="referenceImage",required=false) MultipartFile referenceImage,HttpSession session,Model model)throws IOException{addBrand(model);if(errors.hasErrors()){model.addAttribute("error",errors.getFieldError().getDefaultMessage());return "index";} NewsArticle article=generator.generate(request.getRawNews(),request.getDate(),request.getLocation(),request.getSection());String image=storage.store(mainImage);String reference=storage.store(referenceImage);if(image!=null)article.setMainImage(image);session.setAttribute("article",article);session.setAttribute("referenceImage",reference);return "redirect:/preview";}
@GetMapping("/preview") public String preview(HttpSession session,Model model){NewsArticle a=(NewsArticle)session.getAttribute("article");if(a==null)return "redirect:/";addBrand(model);model.addAttribute("article",a);model.addAttribute("referenceImage",session.getAttribute("referenceImage"));return "newspaper";}
@GetMapping("/download/pdf") public ResponseEntity<byte[]> downloadPdf(HttpSession session)throws IOException{NewsArticle a=(NewsArticle)session.getAttribute("article");if(a==null)return ResponseEntity.notFound().build();byte[] pdf=pdfService.render(a,brand,tagline,location,slogan);return ResponseEntity.ok().contentType(MediaType.APPLICATION_PDF).header(HttpHeaders.CONTENT_DISPOSITION,ContentDisposition.attachment().filename("bheemnagar-times-article.pdf").build().toString()).body(pdf);}
private void addBrand(Model model){model.addAttribute("brand",brand);model.addAttribute("tagline",tagline);model.addAttribute("location",location);model.addAttribute("slogan",slogan);}
}